### ISSUE TITLE
unsupported Compose file version: 3.7 (please support this soon)

### ISSUE THREAD

**Issue by 1c7** [codefresh-io/remote-docker#8]
### What I am trying to do
Deploy Docker Swarm with Codefresh
I am following these step: https://codefresh.io/docs/docs/deploy-your-containers/docker-swarm/
![image](https://user-images.githubusercontent.com/1804755/52534003-a8a09d80-2d76-11e9-82e2-13729359d6e6.png)

### A bit more background info
I am using a sample Ruby on Rails 5 app (create with `rails new ...etc`)
because I am trying if codefresh work for me. if it doesn't, I am gonna use Buddy
I am trying to build a CI/CD workflow with Github -> CodeFresh -> Docker Swarm(it run on my Azure machine)

### What actually happen
Error message: `unsupported Compose file version: 3.4`
![image](https://user-images.githubusercontent.com/1804755/52533951-0f718700-2d76-11e9-8372-8c6c9a98c986.png)

# codefresh.yml
![image](https://user-images.githubusercontent.com/1804755/52533768-bd2f6680-2d73-11e9-9570-95a6040b0f0a.png)
the point here is I am using `codefresh/remote-docker` image.
I know the `- docker info` and `- rdocker help` doesn't work, I already remove them. I am just trying to debug issue with these 2 line.

# docker-stack.yml
![image](https://user-images.githubusercontent.com/1804755/52533769-c587a180-2d73-11e9-8e51-3198761fcbe1.png)
the screenshot here showing 3.7 but previous image showing 3.4 because I take screenshot after create this issue, I can't find that 3.7 error log. so I just screenshot that 3.4 error as example

both `version 3.4` and `version 3.7` not working

I guess you guys are focusing on Kubenetes? 
I am trying to deploy with Docker swarm.

**Comment by 1c7** [comment]
https://codefresh.io/docs/docs/deploy-your-containers/docker-swarm/
I am following these step

**Comment by 1c7** [comment]
`version: '3.1'` work fine

![image](https://user-images.githubusercontent.com/1804755/52533931-d6391700-2d75-11e9-8d80-3e84d6b43a0a.png)

**Comment by 1c7** [comment]
### I hope `codefresh/remote-docker` can support newest docker-compose version soon

![image](https://user-images.githubusercontent.com/1804755/52533924-c3264700-2d75-11e9-9e10-ce52bbb3ac89.png)
https://docs.docker.com/compose/compose-file/

Thanks

**Comment by 1c7** [comment]
#  Conclusion
For now, docker compose `version 3.1` work fine for me. 

**But I hope Codefresh can support higher version soon (like 3.7)**    
because I want to use feature provide by higher version

for example
Version 3.4 provide `order` and other config that help me do 0 downtime deployment
![image](https://user-images.githubusercontent.com/1804755/52534071-9ffc9700-2d77-11e9-8331-b8d08eeeca6c.png)

**Comment by 1c7** [comment]
no one care apparently.
and I am not using CodeFresh at the moment.
I am gonna close this issue

**Comment by laukstein** [comment]
Why Codefresh still doesn't support docker compose v3.7?
